name: hummingbird
channels:
- birdhouse
- defaults
dependencies:
- python=3.7
- pip
# pywps
- jinja2
- click
- psutil
#- xarray
#- netcdf4
# compliance checker ioos
#- compliance-checker
-  cf-units
# tests
- pytest
- pip:
  - -e git+https://github.com/geopython/pywps@master#egg=pywps
  - compliance-checker
